const { initDb } = require('./database/db');

const new_mappings = [
  // Action Table
  ['Action_Table', 'HbA1c', 'CPT', '83036', 'PC009, PC010'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92134', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92132', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92133', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92136', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92242', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92265', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92270', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92283', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92284', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92285', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92230', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92235', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92260', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92499', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '95060', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92240', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92250', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92227', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92228', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92002', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92004', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92012', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92014', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92018', 'PC012'],
  ['Action_Table', 'Eye_Exam', 'CPT', '92019', 'PC012'],
  ['Action_Table', 'Nephropathy', 'CPT', '82043', 'PC013, PC016'],
  ['Action_Table', 'Nephropathy', 'CPT', '82570', 'PC013, PC016'],
  ['Action_Table', 'Nephropathy', 'CPT', '82042', 'PC013, PC016'],
  ['Action_Table', 'Nephropathy', 'CPT', '82044', 'PC013, PC016'],
  ['Action_Table', 'Nephropathy', 'CPT', '82565', 'PC013, PC016'],
  ['Action_Table', 'Autism_Screen', 'CPT', '96110', 'PC021'],
  ['Action_Table', 'Autism_Screen', 'ICD-10', 'Z13.4', 'PC021'],
  ['Action_Table', 'Dyslipidemia', 'CPT', '80061', 'PC024'],
  ['Action_Table', 'Dyslipidemia', 'CPT', '82465', 'PC024'],
  ['Action_Table', 'Dyslipidemia', 'CPT', '83718', 'PC024'],
  ['Action_Table', 'Foot_Exam', 'CPT', '2028F', 'PC011'],
  ['Action_Table', 'Foot_Exam', 'CPT', '99203', 'PC011 (Requires specific E&M modifier/clinic rules)'],

  // Mental Health Inclusions
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F01.51', 'Vascular dementia with behavioral disturbance'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F32.0', 'Major depressive disorder, single episode, mild'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F32.1', 'Major depressive disorder, single episode, moderate'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F32.2', 'Major depressive disorder, single episode, severe without psychotic features'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F32.3', 'Major depressive disorder, single episode, severe with psychotic features'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F32.4', 'Major depressive disorder, single episode, in partial remission'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F32.5', 'Major depressive disorder, single episode, in full remission'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F32.89', 'Other specified depressive episodes'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F32.9', 'Major depressive disorder, single episode, unspecified'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F33.0', 'Major depressive disorder, recurrent, mild'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F33.1', 'Major depressive disorder, recurrent, moderate'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F33.2', 'Major depressive disorder, recurrent severe without psychotic features'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F33.3', 'Major depressive disorder, recurrent, severe with psychotic symptoms'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F33.40', 'Major depressive disorder, recurrent, in remission, unspecified'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F33.41', 'Major depressive disorder, recurrent, in partial remission'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F33.42', 'Major depressive disorder, recurrent, in full remission'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F33.8', 'Other recurrent depressive disorders'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F33.9', 'Major depressive disorder, recurrent, unspecified'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F34.1', 'Dysthymic disorder'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F34.81', 'Disruptive mood dysregulation disorder'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F34.89', 'Other specified persistent mood disorders'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F43.21', 'Adjustment disorder with depressed mood'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F43.23', 'Adjustment disorder with mixed anxiety and depressed mood'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'F53', 'Puerperal psychosis'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'O90.6', 'Postpartum mood disturbance'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'O99.340', 'Other mental disorders complicating pregnancy'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'O99.341', 'Other mental disorders complicating pregnancy'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'O99.342', 'Other mental disorders complicating pregnancy'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'O99.343', 'Other mental disorders complicating pregnancy'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'O99.344', 'Other mental disorders complicating childbirth'],
  ['Disease_Group', 'Depression_Inc', 'ICD-10', 'O99.345', 'Other mental disorders complicating the puerperium'],

  // Mental Health Exclusions
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.10', 'Bipolar disorder, current episode manic without psychotic features, unspecified'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.11', 'Bipolar disorder, current episode manic without psychotic features, mild'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.12', 'Bipolar disorder, current episode manic without psychotic features, moderate'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.13', 'Bipolar disorder, current episode manic without psychotic features, severe'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.2', 'Bipolar disorder, current episode manic severe with psychotic features'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.30', 'Bipolar disorder, current episode depressed, mild or moderate severity, unspecified'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.31', 'Bipolar disorder, current episode depressed, mild'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.32', 'Bipolar disorder, current episode depressed, moderate'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.4', 'Bipolar disorder, current episode depressed, severe, without psychotic features'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.5', 'Bipolar disorder, current episode depressed, severe, with psychotic features'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.60', 'Bipolar disorder, current episode mixed, unspecified'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.61', 'Bipolar disorder, current episode mixed, mild'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.62', 'Bipolar disorder, current episode mixed, moderate'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.63', 'Bipolar disorder, current episode mixed, severe, without psychotic features'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.64', 'Bipolar disorder, current episode mixed, severe, with psychotic features'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.70', 'Bipolar disorder, currently in remission, most recent episode unspecified'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.71', 'Bipolar disorder, in partial remission, most recent episode manic'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.72', 'Bipolar disorder, in full remission, most recent episode manic'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.73', 'Bipolar disorder, in partial remission, most recent episode depressed'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.74', 'Bipolar disorder, in full remission, most recent episode depressed'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.75', 'Bipolar disorder, in partial remission, most recent episode mixed'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.76', 'Bipolar disorder, in full remission, most recent episode mixed'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.77', 'Bipolar disorder, in partial remission, most recent episode hypomanic'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.78', 'Bipolar disorder, in full remission, most recent episode hypomanic'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.81', 'Bipolar II disorder'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.89', 'Other bipolar disorder'],
  ['Exclusion_Group', 'Bipolar_Exc', 'ICD-10', 'F31.9', 'Bipolar disorder, unspecified']
];

initDb().then(async db => {
  for (const row of new_mappings) {
    await db.run('INSERT INTO code_mappings (mapping_type, group_name, code_type, code, description) VALUES (?, ?, ?, ?, ?)', row);
  }
  console.log('Successfully added new code mappings');
}).catch(console.error);
